let tasks=[];
const states={'pendiente':'Pendiente','en-curso':'En curso','completada':'Completada'};
async function api(path,options={}){const r=await fetch(path,options);if(r.status===204)return;const data=await r.json();if(!r.ok)throw Error(data.error||'No se pudo completar la operación.');return data;}
function showError(err){document.querySelector('#error').textContent=err.message;}
async function load(){const d=await api('/api/tasks');tasks=d.tasks;render();}
function render(){document.querySelector('#total').textContent=tasks.length;document.querySelector('#active').textContent=tasks.filter(t=>t.status!=='completada').length;document.querySelector('#completed').textContent=tasks.filter(t=>t.status==='completada').length;const container=document.querySelector('#tasks');container.replaceChildren();const filter=document.querySelector('#filter').value;const visible=tasks.filter(t=>filter==='all'||t.status===filter);if(!visible.length){const empty=document.createElement('div');empty.className='empty';const strong=document.createElement('strong');strong.textContent=tasks.length?'No hay actividades en este estado':'Tu próximo objetivo va aquí';const p=document.createElement('p');p.className='sub';p.textContent=tasks.length?'Prueba otro filtro.':'Agrega una actividad para empezar.';empty.append(strong,p);container.append(empty);}visible.forEach(t=>{const row=document.createElement('article');row.className='task';const info=document.createElement('div');const title=document.createElement('h3');title.textContent=t.title;const course=document.createElement('div');course.className='sub';course.textContent=t.course;info.append(title,course);const actions=document.createElement('div');actions.className='task-actions';const select=document.createElement('select');select.setAttribute('aria-label',`Estado de ${t.title}`);Object.entries(states).forEach(([value,label])=>{const o=new Option(label,value);o.selected=t.status===value;select.append(o);});select.addEventListener('change',async()=>{select.disabled=true;try{await api(`/api/tasks/${t.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:select.value})});await load();document.querySelector('#save-status').textContent='Estado guardado.';}catch(err){showError(err);select.value=t.status;}finally{select.disabled=false;}});const del=document.createElement('button');del.className='delete';del.textContent='Eliminar';del.setAttribute('aria-label',`Eliminar ${t.title}`);del.addEventListener('click',async()=>{if(!confirm(`¿Eliminar «${t.title}»?`))return;try{await api(`/api/tasks/${t.id}`,{method:'DELETE'});await load();}catch(err){showError(err);}});actions.append(select,del);row.append(info,actions);container.append(row);});}
document.querySelector('#filter').addEventListener('change',render);
document.querySelector('#task-form').addEventListener('submit',async e=>{e.preventDefault();document.querySelector('#error').textContent='';const button=e.target.querySelector('button');button.disabled=true;try{await api('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:document.querySelector('#title').value,course:document.querySelector('#course').value})});e.target.reset();await load();document.querySelector('#save-status').textContent='Actividad guardada.';}catch(err){showError(err);}finally{button.disabled=false;}});
load().catch(showError);
